name: Autograding Tests
'on':
  - push
  - workflow_dispatch
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Create and Activate Virtual Environment
      run: |
        python -m venv test-env
        source test-env/bin/activate
        echo $VIRTUAL_ENV

    - name: Get pip cache dir
      id: pip-cache
      run: |
        source test-env/bin/activate
        echo $VIRTUAL_ENV
        echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

    - name: pip cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
  
    - name: Setup test environment
      id: setup-env
      run: |
        source test-env/bin/activate
        echo $VIRTUAL_ENV
        pip install -r requirements.txt

    - name: test results
      id: test-results
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test result linear
        setup-command: ". test-env/bin/activate && echo $VIRTUAL_ENV && python -m pip list"
        command: ". test-env/bin/activate && python -m pytest -n auto --json-report --json-report-file=report_linear.json tests/"
        timeout: 2
        max-score: 5

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-RESULTS_RESULTS: "${{steps.test-results.outputs.result}}"
      with:
        runners: test-results

    - name: upload artifacts
      id: artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: plots
        path: |
          ./*.png
          ./*.json
        retention-days: 21
        overwrite: true
